---
- name: Install kubectl
  apt:
    name: kubectl
    state: present
  become: true

- name: Install helm
  get_url:
    url: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
  become: true

- name: Extract helm
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/
    remote_src: true
  become: true

- name: Move helm binary
  command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
  args:
    creates: /usr/local/bin/helm
  become: true
