- name: Baseline test
  hosts: local
  gather_facts: true
  become: false

  tasks:
    - name: Show OS information
      debug:
        msg: "Running on {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Test Ansible execution
      debug:
        msg: "Ansible is working correctly "
